"""empty message

Revision ID: 2946b30b0956
Revises: 
Create Date: 2024-05-01 18:30:04.161899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2946b30b0956'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('wallet', sa.String(length=48), nullable=True),
    sa.Column('ref_id', sa.BIGINT(), nullable=True),
    sa.Column('tasks', postgresql.ARRAY(sa.String(length=10)), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
